title: "[From➡️To]"
body:
  - type: dropdown
    attributes:
      label: 카테고리
      multiple: false
      options:
        - 전체 공지
        - 에러 관련
        - 기타
      default: 0
    validations:
      required: true

  - type: textarea
    id: improvements
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
