title: "[ANNOUNCEMENT]"
body:
  - type: checkboxes
    attributes:
      label: 작성자
      options:
        - label: "근희"
        - label: "경훈"
        - label: "관훈"
        - label: "은미"
        - label: "재민"

  
