title: "[ANNOUNCEMENT]  "
body:
- type: dropdown
  attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
          1.
          2.
          3.
          ...
      render: markdown
    validations:
      required: true
