title: "ERROR"
body:
  - type: checkboxes
    attributes:
      label: 작성자
      options:
        - label: "근희"
        - label: "경훈"
        - label: "관훈"
        - label: "은미"
        - label: "재민"

  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
