title: "ERROR"
body:
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: "근희"
        - label: "경훈"
          required: true
        - label: "관훈"
          required: true
        - label: "은미"
          required: true
        - label: "재민"
