title: "ERROR"
body:
  - type: checkboxes
    attributes:
      label: 작성자
      options:
        - label: "근희"
        - label: "경훈"
        - label: "관훈"
        - label: "은미"
        - label: "재민"

  - type: dropdown
    id: download
    attributes:
      label: 에러내용
      options:
        - "403 에러"
        - "404 에러"
        - "500 에러"
        - "기타"
    validations:
      required: true
